### ISSUE TITLE
bug, docker_cli/dockerimport uses deprecated 'try_remove_after_test' key

### ISSUE THREAD

**Issue by cevich** [autotest/autotest-docker#433]
```python
14:05:48 INFO | 		ERROR	docker/subtests/docker_cli/dockerimport.test_17-of-52	docker/subtests/docker_cli/dockerimport.test_17-of-52	timestamp=1418670348	localtime=Dec 15 14:05:48	Unhandled KeyError: 'try_remove_after_test'
  Traceback (most recent call last):
    File "/var/tmp/autotest/client/shared/test.py", line 442, in _exec
      _cherry_pick_call(self.cleanup, *args, **dargs)
    File "/var/tmp/autotest/client/shared/test.py", line 738, in _cherry_pick_call
      return func(*p_args, **p_dargs)
    File "/var/tmp/autotest/client/tests/docker/dockertest/subtest.py", line 679, in cleanup
      subsubtest.cleanup()
    File "/var/tmp/autotest/client/tests/docker/subtests/docker_cli/dockerimport/truncated.py", line 28, in cleanup
      if self.parent_subtest.config['try_remove_after_test']:
  KeyError: 'try_remove_after_test'
```

**Comment by cevich** [comment]
This was fixed by c4aad6d7cfdcaf307c6a5fdc20f5a069887d3697
